# -*- coding: utf-8 -*-
"""ResumeScreeningModelCVS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qAQYbC4JHI4s4c8hTJjPWWIvT78QjpzQ
"""

# resumescreeningmodelcvs.py
# Clean, API-safe version
# resumescreeningmodelcvs.py
# Completely updated to use real Job Descriptions instead of categories

import spacy
from spacy.cli import download
from sentence_transformers import SentenceTransformer, util
import pdfplumber
import docx
import os

# ======================
# LOAD NLP MODEL
# ======================
try:
    nlp = spacy.load("en_core_web_sm")
except OSError:
    download("en_core_web_sm")
    nlp = spacy.load("en_core_web_sm")


# ======================
# LOAD EMBEDDING MODEL
# ======================
model = SentenceTransformer('all-MiniLM-L6-v2')


# ======================
# PDF + DOCX EXTRACTION
# ======================
def extract_text_from_pdf(path):
    """Extract full text from PDF."""
    text = ""
    with pdfplumber.open(path) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text


def extract_text_from_docx(path):
    """Extract full text from DOCX."""
    document = docx.Document(path)
    return "\n".join([para.text for para in document.paragraphs])


def read_resume(path):
    """Read PDF or DOCX and return extracted text."""
    if path.endswith(".pdf"):
        return extract_text_from_pdf(path)
    elif path.endswith(".docx"):
        return extract_text_from_docx(path)
    else:
        return ""


# ======================
# ENTITY EXTRACTION
# ======================
def extract_entities(text):
    doc = nlp(text)
    skills = [ent.text for ent in doc.ents if ent.label_ in ['ORG', 'PRODUCT']]
    education = [ent.text for ent in doc.ents if ("University" in ent.text or "College" in ent.text)]
    experience = [ent.text for ent in doc.ents if ent.label_ == "DATE"]

    return {
        "skills": list(set(skills)),
        "education": list(set(education)),
        "experience": list(set(experience))
    }


# ======================
# MATCH RESUME → MULTIPLE JOB DESCRIPTIONS
# ======================
def compute_fit_score(resume_text, job_descriptions):
    """
    job_descriptions must be a dictionary:
    {
        "Job Title": "full job description text..."
    }
    """

    resume_embedding = model.encode(resume_text, convert_to_tensor=True)
    results = []

    for job_title, jd_text in job_descriptions.items():
        jd_embedding = model.encode(jd_text, convert_to_tensor=True)
        similarity = util.cos_sim(resume_embedding, jd_embedding).item()
        results.append((job_title, round(similarity, 4)))

    results.sort(key=lambda x: x[1], reverse=True)
    return results


# ======================
# BIAS INDICATORS
# ======================
def flag_bias_indicators(text):
    flagged = []
    keywords = ["age", "gender", "ethnicity", "marital status", "religion"]

    for k in keywords:
        if k.lower() in text.lower():
            flagged.append(k)

    return flagged


# ====================================================================
#    LOCAL TEST MODE (does NOT run in production with Flask)
# ====================================================================
if __name__ == "__main__":
    print("Running resumescreeningmodelcvs.py in TEST MODE...")

    # Example test text
    sample_resume = "I worked at Microsoft in 2020. Graduated from Oxford University."

    # Full job descriptions for testing
    job_descs = {
        "HR": "Responsible for recruitment, onboarding, employee relations, payroll coordination, performance management, HR policy development, and maintaining compliance with labour regulations.",
        "DESIGNER": "Creates visual concepts, graphics, and layouts for digital and print media, using tools like Photoshop, Illustrator, and Figma. Collaborates with teams to create brand-consistent designs.",
        "INFORMATION-TECHNOLOGY": "Develops, maintains, and troubleshoots software systems, networks, databases, and cloud applications. Requires strong programming, systems analysis, and IT infrastructure knowledge.",
        "TEACHER": "Plans and delivers lessons, assesses student progress, manages classroom activities, and develops curriculum materials to support learning outcomes.",
        "ADVOCATE": "Provides legal advice, prepares cases, drafts legal documents, represents clients in court, and interprets laws and regulations.",
        "BUSINESS-DEVELOPMENT": "Identifies new business opportunities, builds client relationships, develops growth strategies, conducts market research, and manages sales pipelines.",
        "HEALTHCARE": "Provides clinical care, manages patient records, assists in diagnosis, monitors patient health, follows healthcare protocols, and collaborates with medical teams.",
        "FITNESS": "Develops workout programs, trains clients, provides nutrition advice, demonstrates exercises, ensures safety, and tracks fitness progress.",
        "AGRICULTURE": "Works on farming operations, including planting, harvesting, irrigation, crop management, soil analysis, and use of agricultural machinery.",
        "BPO": "Handles customer support, technical support, or back-office operations through calls, chats, or emails in a high-volume outsourcing environment.",
        "SALES": "Generates leads, pitches products, negotiates deals, closes sales, manages customer relationships, and meets revenue targets.",
        "CONSULTANT": "Analyzes business challenges, provides strategic recommendations, develops reports, and supports clients in implementing solutions to improve performance.",
        "DIGITAL-MEDIA": "Manages social media content, digital campaigns, analytics, SEO, online branding, and audience engagement across digital platforms.",
        "AUTOMOBILE": "Performs vehicle diagnostics, repairs, maintenance, quality inspections, and uses automotive tools and systems.",
        "CHEF": "Prepares meals, designs menus, oversees kitchen staff, maintains food quality standards, and manages kitchen operations.",
        "FINANCE": "Handles financial reporting, budgeting, auditing, investment analysis, forecasting, accounting, and compliance with financial regulations.",
        "APPAREL": "Manages clothing production, pattern making, garment design, fashion merchandising, textile selection, and quality control.",
        "ENGINEERING": "Designs and develops technical systems, performs CAD modelling, conducts tests, troubleshoots machinery, and improves engineering processes.",
        "ACCOUNTANT": "Manages financial statements, bookkeeping, tax filing, audits, reconciliations, and compliance with accounting standards.",
        "CONSTRUCTION": "Works on building projects, site management, surveying, blueprint interpretation, material coordination, and safety compliance.",
        "PUBLIC-RELATIONS": "Handles media communications, press releases, brand image management, public statements, event coordination, and crisis communication.",
        "BANKING": "Manages customer accounts, loans, transactions, financial advisory, risk assessment, and regulatory compliance within banking systems.",
        "ARTS": "Creates artistic works in mediums such as painting, music, theatre, or writing. Collaborates on creative projects and exhibits work.",
        "AVIATION": "Supports aircraft operations, maintenance, navigation systems, safety checks, flight coordination, and aviation compliance."
    }

    print("\nComputed Fit Scores:")
    print(compute_fit_score(sample_resume, job_descs))

    print("\nExtracted Entities:")
    print(extract_entities(sample_resume))

    print("\nBias Flags:")
    print(flag_bias_indicators(sample_resume))

    print("\nTest complete.")
